// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv7z_4DYre6X8UHvmt6I39_UerM5dcnag',
    appId: '1:967028957352:android:782c6e80f35996bad6a29d',
    messagingSenderId: '967028957352',
    projectId: 'flutter-test-5099a',
    databaseURL: 'https://flutter-test-5099a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-5099a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYVdvvUgnMrL7A2_r4py-DMh72W9ygF9c',
    appId: '1:967028957352:ios:a1d9df5f3c7e862ed6a29d',
    messagingSenderId: '967028957352',
    projectId: 'flutter-test-5099a',
    databaseURL: 'https://flutter-test-5099a-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-test-5099a.firebasestorage.app',
    iosBundleId: 'com.byteVorex.trackAndDeploy',
  );
}
