name: Android Deploy via Fastlane

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: "stable"

      - name: Install dependencies
        run: |
          flutter pub get

      - name: Build APK & Deploy to Firebase
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          FIREBASE_APP_ID_DEV: ${{ secrets.FIREBASE_APP_ID }}
        run: |
          cd android
          bundle install || echo "No Gemfile"
          fastlane deploy
